# Generated by Django 5.1.6 on 2025-06-04 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Является ли администратором')),
                ('is_ai', models.BooleanField(default=False, verbose_name='Используется ли AI')),
                ('chat_history', models.JSONField(blank=True, default=dict, null=True, verbose_name='История переписки пользователя')),
                ('warranty_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные о гарантиях и скриншотах')),
                ('screenshots_count', models.IntegerField(default=0, verbose_name='Количество отправленных скриншотов за день')),
                ('last_screenshot_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата последней отправки скриншота')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение товара')),
                ('instructions', models.TextField(verbose_name='Инструкция по применению')),
                ('FAQ', models.TextField(verbose_name='FAQ')),
                ('warranty', models.TextField(verbose_name='Условия гарантия')),
                ('extended_warranty', models.FloatField(default=1.0, verbose_name='Срок расширенной гарантии (в годах)')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Товар возвращен')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.goods_category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Название товара',
                'verbose_name_plural': 'Названия товаров',
            },
        ),
    ]
