# Generated by Django 5.1.6 on 2025-04-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='avito_api_key',
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('instructions', models.TextField(verbose_name='Инструкция по применению')),
                ('FAQ', models.TextField(verbose_name='FAQ')),
                ('warranty', models.TextField(verbose_name='Условия гарантия')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.goods_category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Название товара',
                'verbose_name_plural': 'Названия товаров',
            },
        ),
    ]
