# Generated by Django 5.1.6 on 2025-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_message_ids',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ID последних сообщений'),
        ),
    ]
