# Generated by Django 5.1.6 on 2025-06-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='is_returned',
        ),
    ]
