# Generated by Django 5.1.6 on 2025-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_last_message_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_message_ids',
        ),
        migrations.AddField(
            model_name='user',
            name='last_message_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID последнего сообщения'),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_count',
            field=models.IntegerField(default=0, verbose_name='Количество сообщений в текущем действии'),
        ),
    ]
