# Generated by Django 5.1.6 on 2025-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_goods_category_remove_user_avito_api_key_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_history',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='История переписки пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ai',
            field=models.BooleanField(default=False, verbose_name='Используется ли AI'),
        ),
    ]
