# Generated by Django 5.1.6 on 2025-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_chat_history_user_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='extended_warranty',
            field=models.TextField(default='Для получения расширенной гарантии оставьте отзыв с оценкой 5 звезд на товар.', verbose_name='Условия расширенной гарантии'),
        ),
        migrations.AddField(
            model_name='user',
            name='extended_warranty_products',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Товары с расширенной гарантией'),
        ),
    ]
