# Generated by Django 5.1.6 on 2025-06-05 09:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_user_last_message_ids_user_last_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goods_category',
            options={'ordering': ['name'], 'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-telegram_id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='extended_warranty',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='Срок расширенной гарантии (в годах)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_returned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Товар возвращен'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='bot.goods_category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='goods_category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Является ли администратором'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ai',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Используется ли AI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_screenshot_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последней отправки скриншота'),
        ),
        migrations.AlterField(
            model_name='user',
            name='messages_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество сообщений в текущем действии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenshots_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отправленных скриншотов за день'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, max_length=35, verbose_name='Имя'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['name'], name='bot_goods_name_825348_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['is_returned'], name='bot_goods_is_retu_a17f36_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['parent_category'], name='bot_goods_parent__cb6e60_idx'),
        ),
        migrations.AddIndex(
            model_name='goods_category',
            index=models.Index(fields=['name'], name='bot_goods_c_name_80f3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_name'], name='bot_user_user_na_3a2663_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_admin'], name='bot_user_is_admi_85c1af_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_ai'], name='bot_user_is_ai_8c14bf_idx'),
        ),
    ]
