# Generated by Django 5.1.6 on 2025-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_goods_faq_remove_goods_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_contact',
            field=models.CharField(blank=True, default='Для связи с администратором напишите на email: admin@example.com', max_length=255, null=True, verbose_name='Контакт администратора'),
        ),
        migrations.AddField(
            model_name='user',
            name='support_contact',
            field=models.CharField(blank=True, default='Для связи с поддержкой напишите на email: support@example.com', max_length=255, null=True, verbose_name='Контакт поддержки'),
        ),
    ]
