# Generated by Django 5.1.6 on 2025-05-15 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_goods_extended_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_screenshot_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последней отправки скриншота'),
        ),
        migrations.AddField(
            model_name='user',
            name='screenshots_count',
            field=models.IntegerField(default=0, verbose_name='Количество отправленных скриншотов за день'),
        ),
    ]
