# Generated by Django 5.1.6 on 2025-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название промпта')),
                ('prompt_text', models.TextField(verbose_name='Текст промпта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='Промпт по умолчанию')),
                ('description', models.TextField(blank=True, help_text='Описание назначения этого промпта', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Промпт ИИ',
                'verbose_name_plural': 'Промпты ИИ',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
