# Generated by Django 5.1.6 on 2025-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_last_screenshot_date_user_screenshots_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extended_warranty_dates',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Даты активации расширенной гарантии'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='extended_warranty',
            field=models.TextField(verbose_name='Условия расширенной гарантии'),
        ),
    ]
