# Generated by Django 5.1.6 on 2025-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_admin_contact_user_support_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_contact', models.CharField(default='Для связи с администратором напишите на email: admin@example.com', max_length=255, verbose_name='Контакт администратора')),
                ('support_contact', models.CharField(default='Для связи с поддержкой напишите на email: support@example.com', max_length=255, verbose_name='Контакт поддержки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контакт администратора',
                'verbose_name_plural': 'Контакты администраторов',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='support_contact',
        ),
    ]
