# Generated by Django 5.1.6 on 2025-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_user_extended_warranty_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extended_warranty_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Информация о товарах с расширенной гарантией'),
        ),
    ]
