# Generated by Django 5.1.6 on 2025-06-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_aipromptusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aipromptusage',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ai_prompt',
        ),
        migrations.RemoveField(
            model_name='aipromptusage',
            name='user',
        ),
        migrations.AddField(
            model_name='goods',
            name='ai_instruction',
            field=models.TextField(blank=True, help_text='Системное сообщение для ИИ при общении по данному товару', null=True, verbose_name='Инструкция для ИИ поддержки'),
        ),
        migrations.DeleteModel(
            name='AIPrompt',
        ),
        migrations.DeleteModel(
            name='AIPromptUsage',
        ),
    ]
