# Generated by Django 5.1.6 on 2025-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_user_extended_warranty_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='extended_warranty',
            field=models.FloatField(default=1.0, verbose_name='Срок расширенной гарантии (в годах)'),
        ),
    ]
