# Generated by Django 5.1.6 on 2025-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_aipromptusage_prompt_remove_user_ai_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание FAQ (необязательно).', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке.', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pdf_file',
            field=models.FileField(help_text='Обязательное поле. Загрузите PDF файл.', upload_to='faq/', verbose_name='PDF файл FAQ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(help_text='Обязательное поле. Введите название FAQ.', max_length=255, verbose_name='Название FAQ'),
        ),
    ]
