# Generated by Django 5.1.6 on 2025-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_goods_extended_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='extended_warranty_dates',
        ),
        migrations.AddField(
            model_name='user',
            name='warranty_screenshots',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Скриншоты отзывов для расширенной гарантии'),
        ),
    ]
