# Generated by Django 5.1.6 on 2025-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_user_extended_warranty_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='extended_warranty_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='extended_warranty_products',
        ),
        migrations.RemoveField(
            model_name='user',
            name='warranty_screenshots',
        ),
        migrations.AddField(
            model_name='user',
            name='warranty_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные о гарантиях и скриншотах'),
        ),
    ]
