# Generated by Django 5.1.6 on 2025-06-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_faq_description_alter_faq_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл.', null=True, upload_to='faq/', verbose_name='PDF файл FAQ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(help_text='Введите название FAQ.', max_length=255, verbose_name='Название FAQ'),
        ),
    ]
