# Generated by Django 5.1.6 on 2025-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_instruction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instruction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='unique_active_instruction_per_product'),
        ),
    ]
