# Generated by Django 5.1.6 on 2025-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Товар возвращен'),
        ),
    ]
