# Generated by Django 5.1.6 on 2025-06-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_instruction_unique_active_instruction_per_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
