# Generated by Django 5.1.6 on 2025-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_force_delete_instruction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
