# Generated by Django 5.1.6 on 2025-06-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_goods_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
