# Generated by Django 5.1.6 on 2025-10-04 19:32

from django.db import migrations


def fix_utf8mb4_encoding(apps, schema_editor):
    """
    Изменяем кодировку всех таблиц приложения bot на utf8mb4
    для поддержки emoji и других 4-байтовых UTF-8 символов
    """
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Получаем список всех таблиц приложения bot
            cursor.execute(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = DATABASE() AND table_name LIKE 'bot_%'"
            )
            tables = cursor.fetchall()
            
            # Изменяем кодировку каждой таблицы
            for (table_name,) in tables:
                try:
                    cursor.execute(
                        f"ALTER TABLE {table_name} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
                    )
                    print(f"Converted {table_name} to utf8mb4")
                except Exception as e:
                    print(f"Error converting {table_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_utf8mb4_encoding, reverse_code=migrations.RunPython.noop),
    ]
